# Generated by Django 5.1.7 on 2025-04-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0002_guide_route_tourist_travelagency_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='ota_user',
        ),
    ]
